#! /bin/sh

currentlevel=$(pamixer --get-volume-human)
mutestatus=$(pamixer --get-mute)

if [ $currentlevel = 0% ];
then
	echo "Muted"
	#echo "🔇 no"
elif [ $mutestatus = true ];
then
	echo "Muted"
	#echo "🔇 no"
elif [ "$(echo "$currentlevel" | tr -d "%")" -le " 50" ];
then
	echo "$currentlevel"
	#echo "🔉 $currentlevel"


elif [ "$(echo "$currentlevel" | tr -d "%")" -ge " 50" ];
then
	echo " $currentlevel"
	#echo "🔊 $currentlevel"
fi

