#!/usr/bin/env bash
#
# Script name: dmlogout
# Description: Logout, shutdown, reboot or lock screen.
# Dependencies: dmenu, systemd, slock, notify-send
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: Derek Taylor, 
#               Simon Ingelsson

# Define LOCKER in .xprofile to set to different LOCKER program
: "${LOCKER:=slock}"

# An array of options to choose.
declare -a options=(
"1. Lock screen"
"2. Logout"
#"3. Restart dwm"
"3. Reboot"
"4. Suspend"
"5. Power off"
"6. Quit"
)

# We use "printf '%s\n'" to format the array one item to a line.
choice=$(printf '%s\n' "${options[@]}" | dmenu -i -l 7 -p 'Shutdown menu:' "${@}")


# What to do when/if we choose one of the options.
case $choice in
    '1. Lock screen')
        ${LOCKER}
        ;;
	
    '2. Logout')
        if [[ "$(echo -e "No\nYes" | dmenu -i -p "${choice}?" "${@}" )" == "Yes" ]]; then
		killall bspwm
	else
            notify-send "User chose not to logout." && exit 1
        fi
        ;;

 #   '3. Restart dwm')
  #      if [[ "$(echo -e "No\nYes" | dmenu -i -p "${choice}?" "${@}" )" == "Yes" ]]; then
   #         killall dwm
    #    else
     #       notify-send "User chose not to restart dwm." && exit 0
      #  fi
       # ;;

    '3. Reboot')
        if [[ "$(echo -e "No\nYes" | dmenu -i -p "${choice}?" "${@}" )" == "Yes" ]]; then
            systemctl reboot
        else
            notify-send "User chose not to reboot." && exit 0
        fi
        ;;

     '4. Suspend')
        if [[ "$(echo -e "No\nYes" | dmenu -i -p "${choice}?" "${@}" )" == "Yes" ]]; then
            systemctl suspend
        else
            notify-send "User chose not to suspend." && exit 0
        fi
        ;;

     '5. Power off')
        if [[ "$(echo -e "No\nYes" | dmenu -i -p "${choice}?" "${@}" )" == "Yes" ]]; then
          systemctl poweroff
        else
            notify-send "User chose not to shutdown." && exit 0
        fi
        ;;
     '6. Quit')
         notify-send "Program terminated." && exit 0
    ;;
        # It is a common practice to use the wildcard asterisk symbol (*) as a final
    # pattern to define the default case. This pattern will always match.
    *)
        exit 0
    ;;
esac
