#! /bin/sh

#currentlevel=$(pulseaudio-ctl | grep 'Volume level' | awk '{print $4$5}')
currentlevel=$(pamixer --get-volume-human)
mutestatus=$(pamixer --get-mute)

if [ $currentlevel = 0% ];
then
	#echo "婢 Muted"
	dunstify -r 5 "婢 Muted"
elif [ $mutestatus = true ];
then
	#echo "婢 Muted"
	dunstify -r 5 "婢 Muted"
elif [ "$(echo "$currentlevel" | tr -d "%")" -le " 50" ];
then
	#echo " $currentlevel"
	dunstify -r 5 "  $currentlevel"


elif [ "$(echo "$currentlevel" | tr -d "%")" -ge " 50" ];
then
	#echo " $currentlevel"
	dunstify -r 5 "  $currentlevel"
fi
