#!/bin/sh
clipmenud &
#feh -z --bg-scale ~/pics/demonslayer
transmission-daemon &
/usr/bin/pipewire &
/usr/bin/pipewire-pulse &
/usr/bin/pipewire-media-session &
redshift -l 30.06263:31.24967 &
killall dunst
exec startxfce4

