#!/bin/sh
setxkbmap -model pc104 -layout us,ar -variant ,, -option grp:alt_shift_toggle &
xsetroot -cursor_name left_ptr &
picom -b &
numlockx on &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dunst &
feh --bg-scale ~/Pictures/walls/dwmcatppuccin.png
clipmenud &
xidlehook --not-when-audio --not-when-fullscreen --timer 1200 "slock" "" &
xss-lock slock &
transmission-daemon &
slstatus &
#redshift -l 30.06263:31.24967 &
while true; do
    # Log stderror to a file 
    #dwm 2> ~/.config/.dwm.log
    # No error logging
dwm >/dev/null 2>&1
done


